name: Publish to NPM
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: NPM
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.13.1
      - run: npm i -D
      - run: npm run test
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
